import { INodeProperties } from 'n8n-workflow';

export const contactOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['contact'] } },
    options: [
      {
        name: 'Create',
        value: 'create',
        action: 'Create a contact',
        description: 'Add a contact (rejects duplicates by externalId/email)',
      },
      {
        name: 'Find',
        value: 'find',
        action: 'Find a contact',
        description: 'Find a contact by email or external ID',
      },
      {
        name: 'Get',
        value: 'get',
        action: 'Get a contact',
      },
      {
        name: 'Get Many',
        value: 'getMany',
        action: 'Get many contacts',
      },
      {
        name: 'Sync',
        value: 'sync',
        action: 'Sync a contact',
        description: 'Create or update by externalId/email',
      },
    ],
    default: 'create',
  },
];

export const contactFields: INodeProperties[] = [
  {
    displayName: 'Contact List Name or ID',
    name: 'listId',
    type: 'options',
    typeOptions: { loadOptionsMethod: 'getContactLists' },
    default: '',
    required: true,
    description: 'The Cardly contact list. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
    displayOptions: { show: { resource: ['contact'] } },
  },
  {
    displayName: 'First Name',
    name: 'firstName',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['contact'], operation: ['create', 'sync', 'update'] } },
    description: 'First name of the contact',
  },
  {
    displayName: 'Address',
    name: 'address',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['contact'], operation: ['create', 'sync', 'update'] } },
    description: 'Street address of the contact',
  },
  {
    displayName: 'Locality (City/Suburb)',
    name: 'locality',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['contact'], operation: ['create', 'sync', 'update'] } },
    description: 'City or suburb of the contact',
  },
  {
    displayName: 'Country',
    name: 'country',
    type: 'string',
    default: '',
    required: true,
    description: '2-character ISO country code, e.g. US',
    displayOptions: { show: { resource: ['contact'], operation: ['create', 'sync', 'update'] } },
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    displayOptions: { show: { resource: ['contact'], operation: ['create', 'sync', 'update'] } },
    options: [
      { displayName: 'Address 2', name: 'address2', type: 'string', default: '', description: 'Second address line' },
      { displayName: 'Company', name: 'company', type: 'string', default: '', description: 'Company name of the contact' },
      {
        displayName: 'Custom Fields',
        name: 'fields',
        type: 'fixedCollection',
        default: {},
        typeOptions: { multipleValues: true },
        placeholder: 'Add Field',
        description: 'Custom list fields keyed by Cardly field code',
        options: [
          {
            name: 'field',
            displayName: 'Field',
            values: [
              { displayName: 'Field Code', name: 'key', type: 'string', default: '' },
              { displayName: 'Value', name: 'value', type: 'string', default: '' },
            ],
          },
        ],
      },
      {
        displayName: 'Email',
        name: 'email',
        type: 'string',
        default: '',
        placeholder: 'name@email.com',
        description: 'Email address of the contact',
      },
      { displayName: 'External ID', name: 'externalId', type: 'string', default: '', description: 'External identifier to match on for sync' },
      { displayName: 'Last Name', name: 'lastName', type: 'string', default: '', description: 'Last name of the contact' },
      {
        displayName: 'Postcode',
        name: 'postcode',
        type: 'string',
        default: '',
        description: 'Conditionally required by country',
      },
      {
        displayName: 'Region',
        name: 'region',
        type: 'string',
        default: '',
        description: 'State/province. Conditionally required by country.',
      },
    ],
  },
  {
    displayName: 'Contact ID',
    name: 'contactId',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['contact'], operation: ['get'] } },
  },
  {
    displayName: 'Query',
    name: 'query',
    type: 'string',
    default: '',
    required: true,
    description: 'Email address or external ID to search for',
    displayOptions: { show: { resource: ['contact'], operation: ['find'] } },
  },
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    default: false,
    displayOptions: { show: { resource: ['contact'], operation: ['getMany'] } },
    description: 'Whether to return all results or only up to a given limit',
  },
  {
    displayName: 'Limit',
    name: 'limit',
    type: 'number',
    default: 50,
    typeOptions: { minValue: 1 },
    displayOptions: { show: { resource: ['contact'], operation: ['getMany'], returnAll: [false] } },
    description: 'Max number of results to return',
  },
];
